version: '3.7'

services:
  codrr_pg:
    image: postgres:15.2
    container_name: codrr_pg
    restart: always
    environment:
      POSTGRES_DB: codrrdb
      POSTGRES_USER: leoneldev
      POSTGRES_PASSWORD: leoneldev
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
